/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp6_detodo;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emanuel Sosa
 */
public class Busq_rubro extends javax.swing.JInternalFrame {
  private final DefaultTableModel modelo= new DefaultTableModel(){
    public boolean isCellEditable(int f,int c){
    return false;
    }
    };
    /**
     * Creates new form Busq_rubro
     */
    public Busq_rubro() {
        initComponents();
        armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTProductos = new javax.swing.JTable();
        jRubros = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        jLabel1.setText("Busqueda por rubro");

        jTProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTProductos);

        jRubros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LIMPIEZA", "COMESTIBLE", "PERFUMERIA" }));
        jRubros.setSelectedIndex(-1);
        jRubros.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRubrosItemStateChanged(evt);
            }
        });
        jRubros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRubrosActionPerformed(evt);
            }
        });

        jLabel2.setText("Elegir rubro:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRubros, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRubros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRubrosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRubrosItemStateChanged
        // TODO add your handling code here:
  borrarFilas();
         for(Producto p: DeTodo.listaProducto){
           if(jRubros.getSelectedItem().toString().equalsIgnoreCase(p.getRubro().toString())){
             modelo.addRow(new Object[]{
                p.getCodigo(),
                    p.getDescripcion(),
                    p.getPrecio(),
                    p.getStock(),
                     p.getRubro()
                });
           }
        }
    }//GEN-LAST:event_jRubrosItemStateChanged

    private void jRubrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRubrosActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jRubrosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> jRubros;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTProductos;
    // End of variables declaration//GEN-END:variables
public void armarCabecera(){
modelo.addColumn("Codigo");
modelo.addColumn("Descripcion");
modelo.addColumn("Precio");
modelo.addColumn("Stock");
modelo.addColumn("Categoria");
jTProductos.setModel(modelo);
} 
public void borrarFilas(){
int filas=jTProductos.getRowCount()-1;
    for (int f=filas;f>=0;f--) {
        modelo.removeRow(f);
    }
}
}
