/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp6_detodo;

import java.util.TreeSet;

/**
 *
 * @author Emanuel Sosa
 */
public class DeTodo extends javax.swing.JFrame {
    
public static TreeSet<Producto> listaProducto=new TreeSet<>();
    /**
     * Creates new form DeTodo
     */
    public DeTodo() {
        initComponents();
       cargarproducto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JProducto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jPorRubro = new javax.swing.JMenuItem();
        jPorNombre = new javax.swing.JMenuItem();
        jPorPrecio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 600));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 916, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );

        jMenu1.setText("Administracion");

        JProducto.setText("Productos");
        JProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JProductoActionPerformed(evt);
            }
        });
        jMenu1.add(JProducto);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consulta");

        jPorRubro.setText("Por rubro");
        jPorRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPorRubroActionPerformed(evt);
            }
        });
        jMenu2.add(jPorRubro);

        jPorNombre.setText("Por nombre  ");
        jPorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPorNombreActionPerformed(evt);
            }
        });
        jMenu2.add(jPorNombre);

        jPorPrecio.setText("Por precio");
        jPorPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPorPrecioActionPerformed(evt);
            }
        });
        jMenu2.add(jPorPrecio);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPorRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPorRubroActionPerformed
        // TODO add your handling code here:
         escritorio.removeAll();
        escritorio.repaint();
        Busq_rubro busqueda_rubro=new Busq_rubro();
        busqueda_rubro.setVisible(true);
        escritorio.add(busqueda_rubro);
       escritorio.moveToFront(busqueda_rubro);
    }//GEN-LAST:event_jPorRubroActionPerformed

    private void jPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPorNombreActionPerformed

        escritorio.removeAll();
        escritorio.repaint();
        Busq_nombre busqueda_nombre=new Busq_nombre();
        busqueda_nombre.setVisible(true);
        escritorio.add(busqueda_nombre);
       escritorio.moveToFront(busqueda_nombre);
// TODO add your handling code here:
    }//GEN-LAST:event_jPorNombreActionPerformed

    private void jPorPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPorPrecioActionPerformed
        // TODO add your handling code here:
         escritorio.removeAll();
        escritorio.repaint();
         Busq_precio busqueda_precio=new Busq_precio();
        busqueda_precio.setVisible(true);
        escritorio.add(busqueda_precio);
       escritorio.moveToFront(busqueda_precio);
    }//GEN-LAST:event_jPorPrecioActionPerformed

    private void JProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JProductoActionPerformed
        // TODO add your handling code here:
          escritorio.removeAll();
        escritorio.repaint();
         GestionProductos gestor=new GestionProductos();
        gestor.setVisible(true);
        escritorio.add(gestor);
       escritorio.moveToFront(gestor);
    }//GEN-LAST:event_JProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeTodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeTodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeTodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeTodo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeTodo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JProducto;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jPorNombre;
    private javax.swing.JMenuItem jPorPrecio;
    private javax.swing.JMenuItem jPorRubro;
    // End of variables declaration//GEN-END:variables
private void cargarproducto(){
     DeTodo.listaProducto.add(new Producto(123, "prueba", 456, 23, Categoria.PERFUMERIA));
}
}
